HPE/terraform-provider-hpe

- cmd/terraform-provider-hpe/main.go
This gives an example of how to integrate a new subprovider,
so that it will be compiled into the hpe provider.
> Add morpheus subprovider to main

- internal/subproviders/morpheus/model/model.go
- internal/subproviders/morpheus/morpheus.go
- internal/subproviders/morpheus/morpheus_test.go
Adds a first-pass of a schema for the Morpheus subprovider.
Includes validation to ensure that a password is always specifed along with the username and that the access token is not specified when using user authentication.
> Add a schema for the Morpheus subprovider

- internal/subproviders/morpheus/resources/user/resource.go
- internal/subproviders/morpheus/resources/user/resource_test.go
- internal/subproviders/morpheus/resources/user/user_resource_gen.go
Switch to a write only password. This `password_wo` is not
persisted in the state file.
We also introduce `password_wo_version` which can be used (later) in Update()
to determine if the password has been changed. (This is required because
terraform cannot determine if the write-only password has changed by
examining the state.)
> user resource: write only password

- .github/workflows/format.yaml
- cmd/terraform-provider-hpe/main.go
- internal/provider/provider.go
- internal/subproviders/morpheus/clientfactory/clientfactory.go
- internal/subproviders/morpheus/clientfactory/clientfactory_test.go
- internal/subproviders/morpheus/configure/datasource.go
- internal/subproviders/morpheus/configure/resource.go
- internal/subproviders/morpheus/resources/role/resource.go
- internal/subproviders/morpheus/testhelpers/client.go
This will check whether running formatting
against the code base will produce any changes,
and if changes are detected the job will fail.
This helps prevent checking in go files whose
imports are out of order.
> Add format workflow

- internal/subproviders/morpheus/modifiers/modifiers.go
- internal/subproviders/morpheus/resources/user/resource_test.go
- internal/subproviders/morpheus/resources/user/user_resource_gen.go
This plan modifier ensures that if `password_wo` is missing during
plan it is detected and an error is raised.
`password_wo` is a corner case where it is required for create, but
not for import. We do not raise an error in the import case
(tested by existing test).
> user resource: add plan modifier

- go.mod
- go.sum
- internal/subproviders/morpheus/modifiers/modifiers.go
- internal/subproviders/morpheus/resources/user/resource.go
- internal/subproviders/morpheus/resources/user/user_resource_gen.go
Add basic ability to update user resource.
We add a plan modifier for nullable strings so that during plan
changes from "foo" to `null` will be detected and trigger an update.
We also set a plan modifier on id - this is also so that the correct
update behaviour is achieved. In this case it is to avoid spurious
updates.
Tests have been written but will be in a separate PR to reduce review size.
> user resource: update

- templates/data-sources.md.tmpl
- templates/resources.md.tmpl
The tooling was including the path to import.sh
rather than the contents of import.sh.
> Doc templates - fix import

- docs/resources/morpheus_role.md
- internal/subproviders/morpheus/resources/role/resource.go
- internal/subproviders/morpheus/resources/role/resource_test.go
- internal/subproviders/morpheus/resources/role/schema_gen.go
- internal/subproviders/morpheus/testhelpers/role.go
Adds the ability for a user to set `permissions` for the role they are creating by setting a valid JSON string with the `permissions` attribute.
The provider will correctly compare between API permissions, which are partially computed, and those set by the user.
If permissions are set by the user, then those permissions will be stored in the statefile.
If no permissions are set by the user, then the API-computed permissions will be stored in the statefile.
On import of a Role resource, the existing API permissions will be imported and stored in the statefile.
Adds tests to verify correct behaviour of permissions and import of permissions.
New features:
- Add `permissions` support to Role resource.
- Also add `multitenant_locked`, `landing_url` fields.
- Remove prior restriction on …
> Extend Role resource with permissions support

- internal/subproviders/morpheus/resources/role/resource.go
Currently, trying to unmarshal permissions into the generated SDK POST struct fails because the permissions JSON blob lacks the required `authority` (name) field.
After investigating options for editing generated SDK templates, I think that just using a separate struct to handle the unmarshaling is a better choice. It aligns with the intended usage of the generated SDK API better, making use of the generated setter methods. We still make use of the generated SDK models this way.
This will fix the breaking acceptance tests we've been observing.
> Use intermediary create permissions struct for unmarshaling

- internal/subproviders/morpheus/resources/role/resource.go
We can use this pattern to bypass the JSON unmarshaler implementation of the generated SDK struct which we use in role create.
This means we can continue to use the generated SDK struct without maintaining an additional intermediary struct for unmarshaling.
> Override custom JSON unmarshaler of SDK struct for Role create

- internal/subproviders/morpheus/resources/role/resource_test.go
I previously forgot to add the ignore for permissions on import for this acceptance test, this is needed as there's no way for computed permissions from API import to match user-set permissions.
> fix failing acceptance test for example with legacy provider

- internal/subproviders/morpheus/errors/errors.go
Note: we do not get an SSL error type that we can check back
from the client. (We get wrapped url.Error / string types.)
This is brittle, but if it breaks the behaviour will revert to the
existing behaviour, so no harm will be done in that case.
Some Go projects do custom SSL handling to access the
underlying SSL error. We could consider that in the future.
New, additional output:
```
| tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match foo.example.net"
|
| If you understand the potential security risks of accepting an untrusted server
| certificate, you can bypass this error by setting "insecure = true" in your
| provider configuration. Use this option with caution.
|
| provider "hpe" {
|    morpheus {
|      url = "https://..."
|      . …
```
> Make ssl cert error more informative

- internal/subproviders/morpheus/resources/network/schema_gen.go
Rename some network parameters that are of type `int64`
to be consistent with other similar parameters
> network resource schema: rename pool to pool_id

- internal/subproviders/morpheus/resources/network/schema_gen.go
Switch to _ids naming for consistency with
other schema entries
> network resource schema: rename groups

- internal/subproviders/morpheus/resources/network/schema_gen.go
This reflects a current limitation in the API.
> network resource: force recreate on name change

- internal/subproviders/morpheus/resources/role/resource.go
This PR adds some logic to the ImportState method which allows us to correctly import permissions data from the API.
Effectively, for Create, permissions are completely optional and act as overrides, but on import we get the full set of values returned from the API.
> Fix import behaviour for Role permissions

- internal/subproviders/morpheus/resources/role/resource.go
We've agreed to enforce additional validation of these fields on the provider side.
This cleans up importing of a role, as now in Terraform state the incompatible `default access` level will be stored as null.
Morpheus UI suggests that the unsupported `default access` level for the given role type should not be accessible to a user.
> Perform role type validation on default group/cloud access levels

- internal/subproviders/morpheus/datasources/role/consts/consts.go
- internal/subproviders/morpheus/datasources/role/datasource.go
- internal/subproviders/morpheus/datasources/role/datasource_test.go
- internal/subproviders/morpheus/datasources/role/schema_gen.go
Updates the Role data source to use strongly typed permissions, like the resource does.
Contains the following changes:
- Update the `datasource.go` file for the role resource.
- Update the acceptance test to check that values can be read
- Update the generated `schema_gen.go`
When we read permissions via the data source, we get the entire range of API-computed `feature permissions`, not just those that were overridden by the user. This mirrors the behaviour of how the API responds. For the other fine-grained permissions, it will behave as expected, only reading overridden values as the API presents them.
> Add strongly typed permissions to role datasource

- internal/subproviders/morpheus/resources/network/read.go
We use a DynamicAttribute for the `config` block.
The details of the `config` block cannot be retrieved from the API, so
we have to work around that as best we can.
> network resource: add read

- internal/subproviders/morpheus/constants/constants.go
- internal/subproviders/morpheus/resources/network/delete.go
GCP networks may contain up to 44 subnets when
created. The delete happens synchronously and
may take some time (around one minute). For
this reason we have a custom delete timeout.
Timeouts are usually exposed to users with something like this:
https://github.com/hashicorp/terraform-plugin-framework-timeouts
We can revisit to adopt that pattern "later".
> network resource: add delete

- internal/subproviders/morpheus/resources/network/create.go
We use a dynamic attribute for the `config` block.
All network types will use this `config` block.
> network resource: add create

- internal/subproviders/morpheus/morpheusvalidators/dynamic_attribute_object_validator.go
Add basic validation for `config` type dynamic attributes
This cannot validate much, but it will ensure `{}`s, eg:
```
config = {
foo = "bar"
}
```
and allow raising an error during plan for
```
config = "foo"
```
or
```
config = 1
```
Note that this is not tied to the name `config`, dynamic attributes with any name should work also:
```
foo = {} # ok
foo = 123  # errors
```
> dynamic attribute validation

- internal/subproviders/morpheus/convert/convert.go
`FromSetType` and `FromListType` are intended to be used to convert a terraform set/list to a slice to be used with the API. The functions can currently cause errors if the value is null or unknown when we try to convert the elements.
We don't want these functions to return an error, but instead return an empty slice when set/list contains no elements.
> Return empty slice when Set/List is null or unknown

- internal/subproviders/morpheus/resources/role/schema_gen.go
Picks up some schema changes to allow for `multitenant` and `multitenant_locked` to be stored in state as `null` for a `role_type` of `account`.
> Regen Role schema: Remove bool static default from multitenant fields

- internal/subproviders/morpheus/resources/role/schema_gen.go
- internal/subproviders/morpheus/resources/role/update_test.go
Adds acceptance tests for user and tenant roles.
The tests create a role with all fields filled, and updates those fields. 
Then they test an import.
Finally, they remove the permissions block to make sure nothing breaks by doing so.
> Add acceptance tests for Role update

- internal/subproviders/morpheus/modifiers/boolmodifiers/use_state_for_null_or_unknown.go
This is required to iron out some problems introduced by #215.
If we run `terraform plan` as part of an update, the `multitenant` and `multitenant_locked` fields will be marked as `known after apply` when we modify a field that isn't one of those two.
The built-in `UseStateForUnknown` modifier only covers the case where the planned value is unknown, not null.
Since these fields can be persisted in state as either `true/false` or `null`, with an apply on a `tenant` role maintaining a literal `null` value since we don't want to track it in state, we'll need a slightly modified version of `UseStateForUnknown`.
> Add UseStateForNullOrUnknown Bool plan modifier

- internal/subproviders/morpheus/resources/role/resource.go
- internal/subproviders/morpheus/resources/role/resource_test.go
- internal/subproviders/morpheus/resources/role/schema_gen.go
- internal/subproviders/morpheus/resources/role/update_test.go
This PR removes the changes made to store attributes which are specific to `user` and `tenant` roles in state as null. I'm doing this because of limitations that I encountered with the Terraform Plugin Framework around storing the `multitenant` fields dynamically as either `false/true` for `user` roles and `null` for `tenant` roles. Furthermore, avoiding abstracting the API values for these fields keeps consistency between the data source and resource. With these changes an `import` of a Role resource and a read using the role data source behave identically in what information is presented.
The following fields are affected:
- `multitenant`
- `multitenant_locked`
- `default_cloud_access`
- `default_group_access`
`multitenant` and `multitenant_locked` are now stored in state as `false` for …
> Undo storing user and tenant-specific fields in state as null

- internal/subproviders/morpheus/resources/network/update_test.go
Add initial set of update tests for networks.
We check that individual modified attributes trigger a plan diff.
We check that all modifiable fields get changed on update.
We don't run `apply` for each individual modifiable attribute.
> network resource: add update tests

- internal/subproviders/morpheus/resources/network/delete.go
The previous fix doesn't seem to work. I suspect
I had a stray file on my machine. Rework temporarily.
We need to revisit timeouts generally.
> Fix network resource delete (again)

- internal/subproviders/morpheus/datasources/serviceplan/schema_gen.go
We lost some changes to the generated `schema_gen.go` in #248, this just syncs it with the spec repo.
`max_memory` and `max_storage` have their descriptions updated to be in sync with the spec repo.
> Regen service plan data source schema_gen.go - max_memory and max_storage descriptions

- templates-experimental/data-sources/morpheus_service_plan.md.tmpl
- templates-experimental/resources/morpheus_service_plan.md.tmpl
The rendering of examples was previously not working, this PR fixes them.
> Fix example formatting on service plan documentation

- .gitignore
Reverts HPE/terraform-provider-hpe#250
This is generating unrelated documentation which is increasing the maintenance burden on PRs for very little gain.
> Revert "Remove docs-experimental from .gitignore so that QA can read to the docs"

- internal/subproviders/morpheus/resources/instance/example.tf
- internal/subproviders/morpheus/resources/instance/example.tf.tmpl
- internal/subproviders/morpheus/resources/instance/instance.go
- internal/subproviders/morpheus/resources/instance/resource_test.go
Adds an example of an HVM instance being provisioned through terraform.
Adds a drive by fix for the instance dynamic config caught by the testing.
> Add instance resource example and test

- CHANGELOG.md
- docs/index.md
- templates/index.md.tmpl
Add a known issue for situations where some instance layouts require a minimum number of volumes, warning that in these situations instance creation will fail with an error.
> Add known issue for volumes and some instance layouts

- internal/subproviders/morpheus/resources/user/resource.go
- internal/subproviders/morpheus/resources/user/resource_test.go
On update, if linux_key_pair_id was null it was being set to `0` in the
state file.
This was because IsNull() is actually false when a computed optional
attribute is `null`. (In contrast, IsNull() is true when an optional
attribute is `null`.)
> user resource: fix issue with linux_key_pair_id

- go.mod
- go.sum
- internal/subproviders/morpheus/resources/instance/instance.go
- Bumped go mod to correctly replace mapstructure dependency
- Ran go mod tidy to clean up go.sum
- Updated instance resource to safely access Group ID using new SDK method 
~~Currently no longer panics because of the use of GetGroup over Group.Get() but still throws error for TestAccMorpheusInstanceExampleOk .~~
> Resolving Group ID issues with new SDK version
