HPE/terraform-provider-hpe

.github/workflows/build.yaml
Makefile

There is just enough here to prevent checking in code that won't compile.

Add Makefile and initial CI workflow

---

.github/workflows/lint.yaml
.golangci.yml
Makefile

This uses the newer (v2) golangci-lint

Add linting

---

.github/workflows/build.yaml

May save some mild pain in the future, eg w.r.t string diagnostics.

Bump version of Go in build

---

.github/workflows/build.yaml
.github/workflows/lint.yaml
.github/workflows/test.yaml
go.mod

Commands used:
```
go clean -modcache
go mod edit -go=1.24.1 -toolchain=go1.24.1
go mod tidy
```

Bump go to 1.24.1

---

internal/provider/provider.go
internal/subproviders/morpheus/clientfactory/clientfactory.go
internal/subproviders/morpheus/configure/configure.go
internal/subproviders/morpheus/model/model.go
internal/subproviders/morpheus/morpheus_test.go

Add test where sufficient provider block fields are present.
Functional changes to get this test to pass:
* Update per-resource Configure to handle nil ProviderData
* Change types of model fields

Add additional test

---

internal/provider/provider.go

There is no need to have this capitalized -- lowercase is more typical.

Use lowercase for provider struct name

---

go.mod
go.sum

pick up version with user update operationId fix.

Bump morpheus go sdk

---

internal/subproviders/morpheus/resources/user/resource_test.go

We hardcode each config to make the test logic simpler.
(Make bugs in the tests themselves less likely.)
We test cases where fields which are currently
set to a string value are set back to `null`.
We test the logic of `password_wo` + `password_wo_version`

user resource: add update tests

---

internal/subproviders/morpheus/resources/user/resource_test.go

Also check explicit setting of a field to null

user resource: tweak to update test

---

go.sum
internal/subproviders/morpheus/datasources/network/datasource.go
internal/subproviders/morpheus/morpheus.go

We start with a basic set of attributes (matching the 'legacy' provider.)

Add basic network data source

---

.github/workflows/docs.yaml
Makefile

Now to generate docs:
```
make docs
```
(simpler to remember)

Change Makefile document target to docs

---

internal/subproviders/morpheus/convert/valuetoany_test.go

Test null cases, lists, sets, object, tuples, primitives.

Add tests for ValueToAny

---

go.mod
go.sum

Pick up network create resourcePermission change

Bump morpheus sdk

---

go.mod
go.sum

Picks up changes required for Role update (multitenant, multitenantLocked in PUT).

Bump SDK version

---

internal/subproviders/morpheus/resources/network/import.go
internal/subproviders/morpheus/resources/network/resource.go

Try splitting into separate files, to make reviewing more granular.
Note: import will not work until Read is implemented.

network resource: add boiler plate and import

---

internal/subproviders/morpheus/resources/network/create.go

Minor readability improvement.

network create: minor style change

---

internal/subproviders/morpheus/resources/role/schema_gen.go

Just for capturing the changes to`role_type` until we make a decision on the set validators in #194

Regenerate Role schema_gen.go - RequiresReplace for role_type

---

internal/subproviders/morpheus/resources/network/validation_test.go

Add basic validation tests to check that any invalid  attributes
will cause a failure at plan time.

network resource: validation tests

---

internal/subproviders/morpheus/resources/network/create_test.go

Add create test for Google Cloud Platform network type

network resource: add GCP test

---

internal/subproviders/morpheus/resources/role/schema_gen.go

Reverts HPE/terraform-provider-hpe#194
After discussion, we decided to not enforce validation of set size on users.

Revert "Regenerate Role schema_gen.go"

---

go.mod
go.sum
internal/subproviders/morpheus/resources/instance/instance.go
internal/subproviders/morpheus/resources/instance/mappings.go
internal/subproviders/morpheus/resources_experimental.go

Adds an instance resource as an experimental resource.

Add instance resource

---

internal/subproviders/morpheus/resources/network/schema_gen.go

The API does not currently fully support this.

network resource: remove ability to set permissions

---

docs/index.md
templates/index.md.tmpl

Add note on Morpheus provider version to use

---

.github/workflows/docs-diff.yaml

We were not failing the job if new files should have been present but were not.

Fix docs diff CI job

---

internal/subproviders/morpheus/resources/instance/schema_gen.go

Adds a require replace plan modifier to all attributes in the instance resource as update functionality is not yet supported.

Add a require replace modifier to instance

---

go.mod
go.sum
internal/subproviders/morpheus/resources/user/resource.go
internal/subproviders/morpheus/resources/user/resource_test.go

This was missing from the openapi spec.

user resource: allow updating receive notifications
